// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name, currency, description, creator_id, event_uuid, created_at, last_updated_at, is_closed
) VALUES (
    $1, $2, $4, $3, gen_random_uuid(), NOW(), NOW(), FALSE
) RETURNING event_id, event_uuid, name, status, description, currency, created_at, last_updated_at, creator_id, is_closed, total_participants, total_transactions, total_expenses
`

type CreateEventParams struct {
	Name        string  `json:"name"`
	Currency    string  `json:"currency"`
	CreatorID   *int64  `json:"creator_id"`
	Description *string `json:"description"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Currency,
		arg.CreatorID,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.EventUuid,
		&i.Name,
		&i.Status,
		&i.Description,
		&i.Currency,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.CreatorID,
		&i.IsClosed,
		&i.TotalParticipants,
		&i.TotalTransactions,
		&i.TotalExpenses,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE event_id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, eventID int64) error {
	_, err := q.db.Exec(ctx, deleteEvent, eventID)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT event_id, event_uuid, name, status, description, currency, created_at, last_updated_at, creator_id, is_closed, total_participants, total_transactions, total_expenses FROM events
WHERE event_id = $1 LIMIT 1
`

func (q *Queries) GetEventByID(ctx context.Context, eventID int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, eventID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.EventUuid,
		&i.Name,
		&i.Status,
		&i.Description,
		&i.Currency,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.CreatorID,
		&i.IsClosed,
		&i.TotalParticipants,
		&i.TotalTransactions,
		&i.TotalExpenses,
	)
	return i, err
}

const getEventByUUID = `-- name: GetEventByUUID :one
SELECT event_id, event_uuid, name, status, description, currency, created_at, last_updated_at, creator_id, is_closed, total_participants, total_transactions, total_expenses FROM events
WHERE event_uuid = $1 LIMIT 1
`

func (q *Queries) GetEventByUUID(ctx context.Context, eventUuid uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByUUID, eventUuid)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.EventUuid,
		&i.Name,
		&i.Status,
		&i.Description,
		&i.Currency,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.CreatorID,
		&i.IsClosed,
		&i.TotalParticipants,
		&i.TotalTransactions,
		&i.TotalExpenses,
	)
	return i, err
}

const listEventsByUserID = `-- name: ListEventsByUserID :many
SELECT e.event_id, e.event_uuid, e.name, e.status, e.description, e.currency, e.created_at, e.last_updated_at, e.creator_id, e.is_closed, e.total_participants, e.total_transactions, e.total_expenses
FROM events e
JOIN participants p ON e.event_id = p.event_id
WHERE p.user_id = $1
ORDER BY e.last_updated_at DESC
`

// Lấy danh sách event mà user đã tham gia
func (q *Queries) ListEventsByUserID(ctx context.Context, userID *int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.EventUuid,
			&i.Name,
			&i.Status,
			&i.Description,
			&i.Currency,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.CreatorID,
			&i.IsClosed,
			&i.TotalParticipants,
			&i.TotalTransactions,
			&i.TotalExpenses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    status = COALESCE($4, status),
    currency = COALESCE($5, currency),
    is_closed = COALESCE($6, is_closed),
    last_updated_at = NOW()
WHERE event_id = $1
RETURNING event_id, event_uuid, name, status, description, currency, created_at, last_updated_at, creator_id, is_closed, total_participants, total_transactions, total_expenses
`

type UpdateEventParams struct {
	EventID     int64   `json:"event_id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Status      *string `json:"status"`
	Currency    *string `json:"currency"`
	IsClosed    *bool   `json:"is_closed"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Currency,
		arg.IsClosed,
	)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.EventUuid,
		&i.Name,
		&i.Status,
		&i.Description,
		&i.Currency,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.CreatorID,
		&i.IsClosed,
		&i.TotalParticipants,
		&i.TotalTransactions,
		&i.TotalExpenses,
	)
	return i, err
}
