// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Collector struct {
	CollectorID   int64              `json:"collector_id"`
	CollectorUuid uuid.UUID          `json:"collector_uuid"`
	EventID       int64              `json:"event_id"`
	ParticipantID *int64             `json:"participant_id"`
	BankName      string             `json:"bank_name"`
	BankAccount   string             `json:"bank_account"`
	BankOwner     string             `json:"bank_owner"`
	AssignedAt    pgtype.Timestamptz `json:"assigned_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	IsActive      bool               `json:"is_active"`
}

type Event struct {
	EventID           int64              `json:"event_id"`
	EventUuid         uuid.UUID          `json:"event_uuid"`
	Name              string             `json:"name"`
	Status            *string            `json:"status"`
	Description       *string            `json:"description"`
	Currency          string             `json:"currency"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastUpdatedAt     pgtype.Timestamptz `json:"last_updated_at"`
	CreatorID         *int64             `json:"creator_id"`
	IsClosed          bool               `json:"is_closed"`
	TotalParticipants int32              `json:"total_participants"`
	TotalTransactions int32              `json:"total_transactions"`
	TotalExpenses     pgtype.Numeric     `json:"total_expenses"`
}

type Expense struct {
	ExpenseID   int64              `json:"expense_id"`
	ExpenseUuid uuid.UUID          `json:"expense_uuid"`
	EventID     int64              `json:"event_id"`
	Description string             `json:"description"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExpenseBeneficiary struct {
	BeneficiaryID   int64          `json:"beneficiary_id"`
	BeneficiaryUuid uuid.UUID      `json:"beneficiary_uuid"`
	ExpenseID       *int64         `json:"expense_id"`
	ParticipantID   *int64         `json:"participant_id"`
	SplitRatio      pgtype.Numeric `json:"split_ratio"`
}

type ExpensePayer struct {
	PayerID       int64          `json:"payer_id"`
	PayerUuid     uuid.UUID      `json:"payer_uuid"`
	ExpenseID     int64          `json:"expense_id"`
	ParticipantID *int64         `json:"participant_id"`
	PaidAmount    pgtype.Numeric `json:"paid_amount"`
}

type Participant struct {
	ParticipantID   int64              `json:"participant_id"`
	ParticipantUuid uuid.UUID          `json:"participant_uuid"`
	EventID         int64              `json:"event_id"`
	UserID          *int64             `json:"user_id"`
	Name            string             `json:"name"`
	BankName        *string            `json:"bank_name"`
	BankAccount     *string            `json:"bank_account"`
	BankOwner       *string            `json:"bank_owner"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
}

type Settlement struct {
	SettlementID   int64              `json:"settlement_id"`
	SettlementUuid uuid.UUID          `json:"settlement_uuid"`
	EventID        int64              `json:"event_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PayerID        *int64             `json:"payer_id"`
	ReceiverID     *int64             `json:"receiver_id"`
}

type User struct {
	UserID      int64     `json:"user_id"`
	UserUuid    uuid.UUID `json:"user_uuid"`
	Name        string    `json:"name"`
	Email       *string   `json:"email"`
	Avatar      *string   `json:"avatar"`
	PhoneNumber *string   `json:"phone_number"`
	Password    string    `json:"password"`
	BankName    *string   `json:"bank_name"`
	BankAccount *string   `json:"bank_account"`
	BankOwner   *string   `json:"bank_owner"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
