// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package database

import (
	"context"
	"time"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, text, event_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, text, is_read, event_id, created_at
`

type CreateNotificationParams struct {
	UserID  int64  `json:"user_id"`
	Text    string `json:"text"`
	EventID *int64 `json:"event_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Text, arg.EventID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.IsRead,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationsByUserID = `-- name: GetNotificationsByUserID :many
SELECT 
    n.id, 
    n.user_id, 
    n.text, 
    n.is_read, 
    COALESCE(e.event_uuid::text, '') AS event_uuid, 
    n.created_at
FROM notifications n
LEFT JOIN events e ON n.event_id = e.event_id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT 50
`

type GetNotificationsByUserIDRow struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	Text      string      `json:"text"`
	IsRead    bool        `json:"is_read"`
	EventUuid interface{} `json:"event_uuid"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) GetNotificationsByUserID(ctx context.Context, userID int64) ([]GetNotificationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getNotificationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsByUserIDRow
	for rows.Next() {
		var i GetNotificationsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.IsRead,
			&i.EventUuid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, userID)
	return err
}
