// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, email, password, phone_number, bank_name, bank_account, bank_owner
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING user_id, user_uuid, name, email, avatar, phone_number, password, bank_name, bank_account, bank_owner, created_at, updated_at
`

type CreateUserParams struct {
	Name        string  `json:"name"`
	Email       *string `json:"email"`
	Password    string  `json:"password"`
	PhoneNumber *string `json:"phone_number"`
	BankName    *string `json:"bank_name"`
	BankAccount *string `json:"bank_account"`
	BankOwner   *string `json:"bank_owner"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.BankName,
		arg.BankAccount,
		arg.BankOwner,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.PhoneNumber,
		&i.Password,
		&i.BankName,
		&i.BankAccount,
		&i.BankOwner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_uuid, name, email, avatar, phone_number, password, bank_name, bank_account, bank_owner, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.PhoneNumber,
		&i.Password,
		&i.BankName,
		&i.BankAccount,
		&i.BankOwner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_uuid, name, email, avatar, phone_number, password, bank_name, bank_account, bank_owner, created_at, updated_at FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.PhoneNumber,
		&i.Password,
		&i.BankName,
		&i.BankAccount,
		&i.BankOwner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    name = COALESCE($2, name),
    avatar = COALESCE($3, avatar),
    phone_number = COALESCE($4, phone_number),
    bank_name = COALESCE($5, bank_name),
    bank_account = COALESCE($6, bank_account),
    bank_owner = COALESCE($7, bank_owner)
WHERE user_id = $1
RETURNING user_id, user_uuid, name, email, avatar, phone_number, password, bank_name, bank_account, bank_owner, created_at, updated_at
`

type UpdateUserParams struct {
	UserID      int64   `json:"user_id"`
	Name        *string `json:"name"`
	Avatar      *string `json:"avatar"`
	PhoneNumber *string `json:"phone_number"`
	BankName    *string `json:"bank_name"`
	BankAccount *string `json:"bank_account"`
	BankOwner   *string `json:"bank_owner"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Name,
		arg.Avatar,
		arg.PhoneNumber,
		arg.BankName,
		arg.BankAccount,
		arg.BankOwner,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.PhoneNumber,
		&i.Password,
		&i.BankName,
		&i.BankAccount,
		&i.BankOwner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users
SET avatar = $2
WHERE user_id = $1
RETURNING user_id, user_uuid, name, email, avatar, phone_number, password, bank_name, bank_account, bank_owner, created_at, updated_at
`

type UpdateUserAvatarParams struct {
	UserID int64   `json:"user_id"`
	Avatar *string `json:"avatar"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.UserID, arg.Avatar)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.PhoneNumber,
		&i.Password,
		&i.BankName,
		&i.BankAccount,
		&i.BankOwner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
